name = "sciencelog-ai"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[vars]
PROVIDER = "deepseek"
MODEL = "deepseek-chat"

[[kv_namespaces]]
binding = "STORAGE"
id = "5247e215f9214855a0034b26ed3033fe"

[[kv_namespaces]]
binding = "KG"
id = "c7886204c80845c6b9568693ed277b75"
