name = "sciencelog-ai"
account_id = ""
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[vars]
PROVIDER = "deepseek"
MODEL = "deepseek-chat"

[[kv_namespaces]]
binding = "STORAGE"
id = "a65f67bcde704f8eba74285bf6f1635a"

[[kv_namespaces]]
binding = "KG"
id = "a65f67bcde704f8eba74285bf6f1635a"
